[options]
addons_path = /opt/dokidoo/odoo/odoo/addons,/opt/dokidoo/odoo/addons,/opt/dokidoo/odoo/custom-addons
db_host = db
db_port = 5432
; Leave db_name = False for intial set up at least.
; There is usually no need to force it here. See https://odoo-development.readthedocs.io/en/latest/admin/dbfilter.html
db_name = False
db_user = odoo
db_password = <db_user password>
